# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagerapp', '0003_role_teamname_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('description', models.TextField(max_length=1000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanagerapp.Project')),
                ('task_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskmanagerapp.StatusCode')),
            ],
        ),
    ]
