# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagerapp', '0005_auto_20160217_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='taskmanagerapp.Project'),
        ),
    ]
